module.exports = class Data1676061966775 {
    name = 'Data1676061966775'

    async up(db) {
        await db.query(`DROP INDEX "public"."IDX_719f45ea2c1a77d0d37330982e"`)
        await db.query(`DROP INDEX "public"."IDX_51b3d83f2acf15644a0c8f1a29"`)
        await db.query(`DROP INDEX "public"."IDX_a30b3120c9834ee3cbdf7ed04b"`)
        await db.query(`DROP INDEX "public"."IDX_3a5719afdbab755d8e954348a4"`)
        await db.query(`CREATE TABLE "mint_event" ("id" character varying NOT NULL, "name" text NOT NULL, "to" text NOT NULL, "amount" numeric NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_c9abd6d2c19a587aac1641c7dee" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2671334b7d21ea440ef34849c2" ON "mint_event" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_7f18a4a857f1a393973677a0da" ON "mint_event" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_c82715e657a5a538375d9fd089" ON "mint_event" ("name") `)
        await db.query(`CREATE INDEX "IDX_76cf264c0f7faf79a25eea5aa6" ON "mint_event" ("to") `)
        await db.query(`CREATE TABLE "mint_finished_event" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_07c283975bfdc8348bcb6cadde4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c85cf190317a2eccc4bf089b07" ON "mint_finished_event" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_9554ebd701cb97d7672d7387dc" ON "mint_finished_event" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_a72034022f99cbb8ffced81a66" ON "mint_finished_event" ("name") `)
        await db.query(`CREATE TABLE "pause_event" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_9def8f2298caec7ba9746c265c4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9319951c5a696505ebaddad330" ON "pause_event" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_b794e2d6840564f0c722ce2751" ON "pause_event" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_1d49fb1740f2e83a7f8bfbe7b9" ON "pause_event" ("name") `)
        await db.query(`CREATE TABLE "unpause_event" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_5655c9563a30e9574dead82e03c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0e34a951d449872859d5f277fa" ON "unpause_event" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_c9324e019ccecd749ae0371f09" ON "unpause_event" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_f5b6305c274f910631eac52c6f" ON "unpause_event" ("name") `)
        await db.query(`CREATE TABLE "burn_event" ("id" character varying NOT NULL, "name" text NOT NULL, "burner" text NOT NULL, "value" numeric NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_28ccbec87579fde72b1ab1eeece" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0399688cc6bafa65bbdbe3c327" ON "burn_event" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_a71866936eb97351678ad61a1c" ON "burn_event" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_ecf485e2967c13491517853b28" ON "burn_event" ("name") `)
        await db.query(`CREATE INDEX "IDX_1804a031789ea62697f1ae1136" ON "burn_event" ("burner") `)
        await db.query(`CREATE TABLE "unpause_function" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_b08bb36dc575640eef99cb89bef" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_bda7a40aafacfe78c71e33833e" ON "unpause_function" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_9f60514e88ad67a06ff6dfe9c1" ON "unpause_function" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_f1f6cfddf8091d084ddac632cd" ON "unpause_function" ("name") `)
        await db.query(`CREATE TABLE "finish_minting_function" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_64451a1e692e51c5ea6526bc820" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_cbe98fd86e0a12115e37cef9e3" ON "finish_minting_function" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_ce7e2a26d9d710d76002184506" ON "finish_minting_function" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_131888bf4a303980ff6dee7cce" ON "finish_minting_function" ("name") `)
        await db.query(`CREATE TABLE "pause_function" ("id" character varying NOT NULL, "name" text NOT NULL, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_d8cc8350e5fc3a1fbb70c138410" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e619bbab75ec51d1904ecf876b" ON "pause_function" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_cc18166cc22da69ef874a38841" ON "pause_function" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_21eaa16bf2260939b4b9c496ee" ON "pause_function" ("name") `)
        await db.query(`CREATE TABLE "transfer_ownership_function" ("id" character varying NOT NULL, "name" text NOT NULL, "new_owner" text, "block_id" character varying, "transaction_id" character varying, CONSTRAINT "PK_a6efa2a18bd6b2f206661fa2a4e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_508a4e3f78a565370b47cafad0" ON "transfer_ownership_function" ("block_id") `)
        await db.query(`CREATE INDEX "IDX_6d3f6a999b2101dd04e57d8045" ON "transfer_ownership_function" ("transaction_id") `)
        await db.query(`CREATE INDEX "IDX_8be661b46a3c78f618e2fa8488" ON "transfer_ownership_function" ("name") `)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "src"`)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "guy"`)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "src"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "dst"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "approve_function" DROP COLUMN "usr"`)
        await db.query(`ALTER TABLE "approve_function" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "src"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "dst"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "mint_function" DROP COLUMN "usr"`)
        await db.query(`ALTER TABLE "mint_function" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "burn_function" DROP COLUMN "usr"`)
        await db.query(`ALTER TABLE "burn_function" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "transfer_function" DROP COLUMN "dst"`)
        await db.query(`ALTER TABLE "transfer_function" DROP COLUMN "wad"`)
        await db.query(`ALTER TABLE "approval_event" ADD "owner" text NOT NULL`)
        await db.query(`ALTER TABLE "approval_event" ADD "spender" text NOT NULL`)
        await db.query(`ALTER TABLE "approval_event" ADD "value" numeric NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "from" text NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "to" text NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "value" numeric NOT NULL`)
        await db.query(`ALTER TABLE "approve_function" ADD "spender" text`)
        await db.query(`ALTER TABLE "approve_function" ADD "value" numeric`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "from" text`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "to" text`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "value" numeric`)
        await db.query(`ALTER TABLE "mint_function" ADD "to" text`)
        await db.query(`ALTER TABLE "mint_function" ADD "amount" numeric`)
        await db.query(`ALTER TABLE "burn_function" ADD "value" numeric`)
        await db.query(`ALTER TABLE "transfer_function" ADD "to" text`)
        await db.query(`ALTER TABLE "transfer_function" ADD "value" numeric`)
        await db.query(`CREATE INDEX "IDX_66738eac40ffe8cb9a983934ee" ON "approval_event" ("owner") `)
        await db.query(`CREATE INDEX "IDX_8639c37d511fdd6b468c0864d2" ON "approval_event" ("spender") `)
        await db.query(`CREATE INDEX "IDX_e3f2115e36145e7e44e40f3d6e" ON "transfer_event" ("from") `)
        await db.query(`CREATE INDEX "IDX_d89c05d6a45f28bb97b161b696" ON "transfer_event" ("to") `)
        await db.query(`ALTER TABLE "mint_event" ADD CONSTRAINT "FK_2671334b7d21ea440ef34849c2b" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint_event" ADD CONSTRAINT "FK_7f18a4a857f1a393973677a0da4" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint_finished_event" ADD CONSTRAINT "FK_c85cf190317a2eccc4bf089b07c" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint_finished_event" ADD CONSTRAINT "FK_9554ebd701cb97d7672d7387dc5" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pause_event" ADD CONSTRAINT "FK_9319951c5a696505ebaddad3306" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pause_event" ADD CONSTRAINT "FK_b794e2d6840564f0c722ce2751d" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "unpause_event" ADD CONSTRAINT "FK_0e34a951d449872859d5f277faa" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "unpause_event" ADD CONSTRAINT "FK_c9324e019ccecd749ae0371f09a" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "burn_event" ADD CONSTRAINT "FK_0399688cc6bafa65bbdbe3c3276" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "burn_event" ADD CONSTRAINT "FK_a71866936eb97351678ad61a1c1" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "unpause_function" ADD CONSTRAINT "FK_bda7a40aafacfe78c71e33833e9" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "unpause_function" ADD CONSTRAINT "FK_9f60514e88ad67a06ff6dfe9c10" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "finish_minting_function" ADD CONSTRAINT "FK_cbe98fd86e0a12115e37cef9e3e" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "finish_minting_function" ADD CONSTRAINT "FK_ce7e2a26d9d710d760021845066" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pause_function" ADD CONSTRAINT "FK_e619bbab75ec51d1904ecf876b9" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pause_function" ADD CONSTRAINT "FK_cc18166cc22da69ef874a38841f" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer_ownership_function" ADD CONSTRAINT "FK_508a4e3f78a565370b47cafad03" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer_ownership_function" ADD CONSTRAINT "FK_6d3f6a999b2101dd04e57d8045e" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`CREATE INDEX "IDX_719f45ea2c1a77d0d37330982e" ON "approval_event" ("src") `)
        await db.query(`CREATE INDEX "IDX_51b3d83f2acf15644a0c8f1a29" ON "approval_event" ("guy") `)
        await db.query(`CREATE INDEX "IDX_a30b3120c9834ee3cbdf7ed04b" ON "transfer_event" ("src") `)
        await db.query(`CREATE INDEX "IDX_3a5719afdbab755d8e954348a4" ON "transfer_event" ("dst") `)
        await db.query(`DROP TABLE "mint_event"`)
        await db.query(`DROP INDEX "public"."IDX_2671334b7d21ea440ef34849c2"`)
        await db.query(`DROP INDEX "public"."IDX_7f18a4a857f1a393973677a0da"`)
        await db.query(`DROP INDEX "public"."IDX_c82715e657a5a538375d9fd089"`)
        await db.query(`DROP INDEX "public"."IDX_76cf264c0f7faf79a25eea5aa6"`)
        await db.query(`DROP TABLE "mint_finished_event"`)
        await db.query(`DROP INDEX "public"."IDX_c85cf190317a2eccc4bf089b07"`)
        await db.query(`DROP INDEX "public"."IDX_9554ebd701cb97d7672d7387dc"`)
        await db.query(`DROP INDEX "public"."IDX_a72034022f99cbb8ffced81a66"`)
        await db.query(`DROP TABLE "pause_event"`)
        await db.query(`DROP INDEX "public"."IDX_9319951c5a696505ebaddad330"`)
        await db.query(`DROP INDEX "public"."IDX_b794e2d6840564f0c722ce2751"`)
        await db.query(`DROP INDEX "public"."IDX_1d49fb1740f2e83a7f8bfbe7b9"`)
        await db.query(`DROP TABLE "unpause_event"`)
        await db.query(`DROP INDEX "public"."IDX_0e34a951d449872859d5f277fa"`)
        await db.query(`DROP INDEX "public"."IDX_c9324e019ccecd749ae0371f09"`)
        await db.query(`DROP INDEX "public"."IDX_f5b6305c274f910631eac52c6f"`)
        await db.query(`DROP TABLE "burn_event"`)
        await db.query(`DROP INDEX "public"."IDX_0399688cc6bafa65bbdbe3c327"`)
        await db.query(`DROP INDEX "public"."IDX_a71866936eb97351678ad61a1c"`)
        await db.query(`DROP INDEX "public"."IDX_ecf485e2967c13491517853b28"`)
        await db.query(`DROP INDEX "public"."IDX_1804a031789ea62697f1ae1136"`)
        await db.query(`DROP TABLE "unpause_function"`)
        await db.query(`DROP INDEX "public"."IDX_bda7a40aafacfe78c71e33833e"`)
        await db.query(`DROP INDEX "public"."IDX_9f60514e88ad67a06ff6dfe9c1"`)
        await db.query(`DROP INDEX "public"."IDX_f1f6cfddf8091d084ddac632cd"`)
        await db.query(`DROP TABLE "finish_minting_function"`)
        await db.query(`DROP INDEX "public"."IDX_cbe98fd86e0a12115e37cef9e3"`)
        await db.query(`DROP INDEX "public"."IDX_ce7e2a26d9d710d76002184506"`)
        await db.query(`DROP INDEX "public"."IDX_131888bf4a303980ff6dee7cce"`)
        await db.query(`DROP TABLE "pause_function"`)
        await db.query(`DROP INDEX "public"."IDX_e619bbab75ec51d1904ecf876b"`)
        await db.query(`DROP INDEX "public"."IDX_cc18166cc22da69ef874a38841"`)
        await db.query(`DROP INDEX "public"."IDX_21eaa16bf2260939b4b9c496ee"`)
        await db.query(`DROP TABLE "transfer_ownership_function"`)
        await db.query(`DROP INDEX "public"."IDX_508a4e3f78a565370b47cafad0"`)
        await db.query(`DROP INDEX "public"."IDX_6d3f6a999b2101dd04e57d8045"`)
        await db.query(`DROP INDEX "public"."IDX_8be661b46a3c78f618e2fa8488"`)
        await db.query(`ALTER TABLE "approval_event" ADD "src" text NOT NULL`)
        await db.query(`ALTER TABLE "approval_event" ADD "guy" text NOT NULL`)
        await db.query(`ALTER TABLE "approval_event" ADD "wad" numeric NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "src" text NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "dst" text NOT NULL`)
        await db.query(`ALTER TABLE "transfer_event" ADD "wad" numeric NOT NULL`)
        await db.query(`ALTER TABLE "approve_function" ADD "usr" text`)
        await db.query(`ALTER TABLE "approve_function" ADD "wad" numeric`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "src" text`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "dst" text`)
        await db.query(`ALTER TABLE "transfer_from_function" ADD "wad" numeric`)
        await db.query(`ALTER TABLE "mint_function" ADD "usr" text`)
        await db.query(`ALTER TABLE "mint_function" ADD "wad" numeric`)
        await db.query(`ALTER TABLE "burn_function" ADD "usr" text`)
        await db.query(`ALTER TABLE "burn_function" ADD "wad" numeric`)
        await db.query(`ALTER TABLE "transfer_function" ADD "dst" text`)
        await db.query(`ALTER TABLE "transfer_function" ADD "wad" numeric`)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "owner"`)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "spender"`)
        await db.query(`ALTER TABLE "approval_event" DROP COLUMN "value"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "from"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "to"`)
        await db.query(`ALTER TABLE "transfer_event" DROP COLUMN "value"`)
        await db.query(`ALTER TABLE "approve_function" DROP COLUMN "spender"`)
        await db.query(`ALTER TABLE "approve_function" DROP COLUMN "value"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "from"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "to"`)
        await db.query(`ALTER TABLE "transfer_from_function" DROP COLUMN "value"`)
        await db.query(`ALTER TABLE "mint_function" DROP COLUMN "to"`)
        await db.query(`ALTER TABLE "mint_function" DROP COLUMN "amount"`)
        await db.query(`ALTER TABLE "burn_function" DROP COLUMN "value"`)
        await db.query(`ALTER TABLE "transfer_function" DROP COLUMN "to"`)
        await db.query(`ALTER TABLE "transfer_function" DROP COLUMN "value"`)
        await db.query(`DROP INDEX "public"."IDX_66738eac40ffe8cb9a983934ee"`)
        await db.query(`DROP INDEX "public"."IDX_8639c37d511fdd6b468c0864d2"`)
        await db.query(`DROP INDEX "public"."IDX_e3f2115e36145e7e44e40f3d6e"`)
        await db.query(`DROP INDEX "public"."IDX_d89c05d6a45f28bb97b161b696"`)
        await db.query(`ALTER TABLE "mint_event" DROP CONSTRAINT "FK_2671334b7d21ea440ef34849c2b"`)
        await db.query(`ALTER TABLE "mint_event" DROP CONSTRAINT "FK_7f18a4a857f1a393973677a0da4"`)
        await db.query(`ALTER TABLE "mint_finished_event" DROP CONSTRAINT "FK_c85cf190317a2eccc4bf089b07c"`)
        await db.query(`ALTER TABLE "mint_finished_event" DROP CONSTRAINT "FK_9554ebd701cb97d7672d7387dc5"`)
        await db.query(`ALTER TABLE "pause_event" DROP CONSTRAINT "FK_9319951c5a696505ebaddad3306"`)
        await db.query(`ALTER TABLE "pause_event" DROP CONSTRAINT "FK_b794e2d6840564f0c722ce2751d"`)
        await db.query(`ALTER TABLE "unpause_event" DROP CONSTRAINT "FK_0e34a951d449872859d5f277faa"`)
        await db.query(`ALTER TABLE "unpause_event" DROP CONSTRAINT "FK_c9324e019ccecd749ae0371f09a"`)
        await db.query(`ALTER TABLE "burn_event" DROP CONSTRAINT "FK_0399688cc6bafa65bbdbe3c3276"`)
        await db.query(`ALTER TABLE "burn_event" DROP CONSTRAINT "FK_a71866936eb97351678ad61a1c1"`)
        await db.query(`ALTER TABLE "unpause_function" DROP CONSTRAINT "FK_bda7a40aafacfe78c71e33833e9"`)
        await db.query(`ALTER TABLE "unpause_function" DROP CONSTRAINT "FK_9f60514e88ad67a06ff6dfe9c10"`)
        await db.query(`ALTER TABLE "finish_minting_function" DROP CONSTRAINT "FK_cbe98fd86e0a12115e37cef9e3e"`)
        await db.query(`ALTER TABLE "finish_minting_function" DROP CONSTRAINT "FK_ce7e2a26d9d710d760021845066"`)
        await db.query(`ALTER TABLE "pause_function" DROP CONSTRAINT "FK_e619bbab75ec51d1904ecf876b9"`)
        await db.query(`ALTER TABLE "pause_function" DROP CONSTRAINT "FK_cc18166cc22da69ef874a38841f"`)
        await db.query(`ALTER TABLE "transfer_ownership_function" DROP CONSTRAINT "FK_508a4e3f78a565370b47cafad03"`)
        await db.query(`ALTER TABLE "transfer_ownership_function" DROP CONSTRAINT "FK_6d3f6a999b2101dd04e57d8045e"`)
    }
}
